include config.mk
all:

clean:

nerd: nerd.py
	awk 'BEGIN {                                                          \
			file="";                                                      \
	        while (getline line < "common.py") file = file "\n" line      \
		}                                                                 \
		/from common import \*/ {                                         \
			print "###### AUTOGENERATED FILE DO NOT EDIT BY HAND ######"; \
			gsub(/^from common import \*$$/, file)                        \
		}                                                                 \
		1' $< > $@

install: all nerd
	mkdir -p ${DESTDIR}${PREFIX}/bin/
	$(foreach file, $(wildcard *.sh), install $(file) ${DESTDIR}${PREFIX}/bin/$(basename $(file));)
	install nerd ${DESTDIR}${PREFIX}/bin/nerd


uninstall:
	$(foreach file, $(wildcard *.sh), rm -f ${DESTDIR}${PREFIX}/bin/$(basename $(file));)
	rm -f ${DESTDIR}${PREFIX}/bin/nerd

.PHONY: all clean install uninstall
