#!/bin/sh

[ -d "$HOME"/Pictures/screenshots/ ] || mkdir -p "$HOME"/Pictures/screenshots/

FILENAME="$(printf "" | dmenu -l 0 )"

if [ -z "$FILENAME" ]; then
    FILENAME="$(date +'%F_0.png')"
else
    FILENAME=$FILENAME.png
fi

COUNTER=0
while [ -f "$HOME"/Pictures/screenshots/"$FILENAME" ]; do
    FILENAME="$(date +'%F')"_"$COUNTER".png
done

killall unclutter
import "$HOME"/Pictures/screenshots/"$FILENAME"
unclutter -b
